// Package market turns nexo's Library into a local Claude Code
// marketplace (plan D1). Plugin-type assets are symlinked into
// ~/.nexo/marketplace/ next to a generated .claude-plugin/
// marketplace.json, so Claude Code installs them through its OWN
// mechanism:
//
//	claude plugin marketplace add ~/.nexo/marketplace
//	claude plugin install <name>@nexo-library
//
// nexo never writes installed_plugins.json or the plugin cache — the
// provider's native installer stays in charge, which is the whole
// point of the Reference strategy.
package market

import (
	"encoding/json"
	"errors"
	"io/fs"
	"path"

	"github.com/melvicsosa/nexo/internal/core/library"
	"github.com/melvicsosa/nexo/internal/core/tx"
	"github.com/melvicsosa/nexo/internal/domain"
	"github.com/melvicsosa/nexo/internal/ports"
)

// Name is the marketplace name Claude Code will know the library by.
const Name = "nexo-library"

// Dir is where the marketplace lives under the state dir.
func Dir(stateDir string) string { return path.Join(stateDir, "marketplace") }

type marketplaceJSON struct {
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Owner       ownerJSON    `json:"owner"`
	Plugins     []pluginJSON `json:"plugins"`
}

type ownerJSON struct {
	Name string `json:"name"`
}

type pluginJSON struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	Version     string `json:"version,omitempty"`
	Source      string `json:"source"`
}

// SyncSteps plans regenerating the marketplace from the library:
// symlink every plugin asset in, drop links whose asset is gone, and
// rewrite marketplace.json. Returns the plugin names it will expose.
func SyncSteps(fsys ports.FS, lib *library.Library, stateDir, owner string) ([]tx.Step, []string, error) {
	assets, err := lib.List()
	if err != nil {
		return nil, nil, err
	}
	dir := Dir(stateDir)
	var steps []tx.Step
	steps = append(steps, tx.MkdirAll(path.Join(dir, ".claude-plugin"), 0o755))

	var plugins []pluginJSON
	var names []string
	wanted := map[string]bool{}
	for _, asset := range assets {
		if asset.Type != domain.TypePlugin {
			continue
		}
		wanted[asset.ID.Name] = true
		names = append(names, asset.ID.Name)
		plugins = append(plugins, pluginJSON{
			Name:        asset.ID.Name,
			Description: asset.Description,
			Version:     asset.Version,
			Source:      "./" + asset.ID.Name,
		})
		linkPath := path.Join(dir, asset.ID.Name)
		target := lib.AssetPath(asset.ID)
		current, err := fsys.Readlink(linkPath)
		switch {
		case err == nil && current == target:
			// already linked correctly
		case err == nil || !isNotExist(fsys, linkPath):
			// wrong link or something else in the way: replace it
			steps = append(steps, tx.Remove(linkPath), tx.Symlink(target, linkPath))
		default:
			steps = append(steps, tx.Symlink(target, linkPath))
		}
	}

	// Drop stale links for plugins no longer in the library.
	if entries, err := fsys.ReadDir(dir); err == nil {
		for _, e := range entries {
			if e.Name() == ".claude-plugin" || wanted[e.Name()] {
				continue
			}
			info, err := fsys.Lstat(path.Join(dir, e.Name()))
			if err == nil && info.Mode()&fs.ModeSymlink != 0 {
				steps = append(steps, tx.Remove(path.Join(dir, e.Name())))
			}
		}
	}

	manifest := marketplaceJSON{
		Name:        Name,
		Description: "Local marketplace generated by nexo from your library",
		Owner:       ownerJSON{Name: owner},
		Plugins:     plugins,
	}
	data, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, nil, err
	}
	data = append(data, '\n')
	steps = append(steps, tx.WriteFile(path.Join(dir, ".claude-plugin", "marketplace.json"), data, 0o644))
	return steps, names, nil
}

func isNotExist(fsys ports.FS, p string) bool {
	_, err := fsys.Lstat(p)
	return errors.Is(err, fs.ErrNotExist)
}
